pool:
  vmImage: 'windows-2022'

trigger:
  batch: 'true'
  branches:
    include:
    - master

variables:
- name: PackageOutputPath
  value: '$(Build.ArtifactStagingDirectory)'
- name: GeneratePackageOnBuild
  value: true

steps:
- template: build/ci/templates/dotnet-install-windows.yml
- template: build/ci/templates/jdk-setup.yml

- task: UseDotNet@2
  displayName: 'Use .Net Core runtime 5.0.3'
  inputs:
    packageType: runtime
    version: 5.0.3

- task: UseDotNet@2
  displayName: 'Use .Net Core runtime 3.1.0'
  inputs:
    packageType: runtime
    version: 3.1.0

- task: gitversion/setup@0
  inputs:
    versionSpec: '5.6.8'

- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: gitversion.yml
  displayName: Use GitVersion

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 5.0.2

- task: MSBuild@1
  inputs:
    solution: Uno.ShowMeTheXAML.sln
    configuration: Release
    platform: 'Any CPU'
    msbuildArguments: /r /p:PackageVersion=$(GitVersion.NuGetVersion)

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: Packages
    PathtoPublish: $(PackageOutputPath)
    publishLocation: Container