<Project Sdk="MSBuild.Sdk.Extras">

	<!-- <Import Project="..\Build.targets" /> -->

	<PropertyGroup>
		<TargetFrameworks>net7.0;net7.0-ios;net7.0-macos;net7.0-android;net7.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);net7.0-windows10.0.19041</TargetFrameworks>
		<OutputType>library</OutputType>
		<RootNamespace>ShowMeTheXAML</RootNamespace>
		<AssemblyName>Uno.ShowMeTheXAML</AssemblyName>
		<Title>Uno.ShowMeTheXAML</Title>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
	</PropertyGroup>

	<PropertyGroup>
		<DefineConstants>$(DefineConstants);__UNO__</DefineConstants>
	</PropertyGroup>
	<ItemGroup Condition="!$(TargetFramework.Contains('-windows'))">
		<Reference Include="System.Xml.Linq" />
		<PackageReference Include="Uno.WinUI" Version="5.0.0-dev.1695" />
	</ItemGroup>


	<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.0" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.755" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Properties\" />
		<Compile Remove="Properties\AssemblyInfo.cs" />
		<Compile Remove="Properties\Resources.Designer.cs" />
		<Compile Remove="Properties\Settings.Designer.cs" />
		<EmbeddedResource Remove="Properties\Resources.resx" />
		<None Remove="Properties\Settings.settings" />
	</ItemGroup>

</Project>