<Project Sdk="Microsoft.NET.Sdk">

	<!-- <Import Project="..\Build.targets" /> -->

	<PropertyGroup>
		<TargetFrameworks>net9.0;net9.0-ios;net9.0-macos;net9.0-android;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
		<OutputType>library</OutputType>
		<RootNamespace>ShowMeTheXAML</RootNamespace>
		<AssemblyName>Uno.ShowMeTheXAML</AssemblyName>
		<Title>Uno.ShowMeTheXAML</Title>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
	</PropertyGroup>

	<PropertyGroup>
		<DefineConstants>$(DefineConstants);__UNO__</DefineConstants>
	</PropertyGroup>
	<ItemGroup Condition="!$(TargetFramework.Contains('-windows'))">
		<PackageReference Include="Uno.WinUI" Version="6.4.242" />
	</ItemGroup>


	<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260101001" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.1-RTM" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Properties\" />
		<Compile Remove="Properties\AssemblyInfo.cs" />
		<Compile Remove="Properties\Resources.Designer.cs" />
		<Compile Remove="Properties\Settings.Designer.cs" />
		<EmbeddedResource Remove="Properties\Resources.resx" />
		<None Remove="Properties\Settings.settings" />
	</ItemGroup>

</Project>