<Project Sdk="MSBuild.Sdk.Extras">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0</TargetFrameworks>
		<PackageId>Uno.ShowMeTheXAML.MSBuild</PackageId>
		<OutputType>Library</OutputType>
		<IsTool>True</IsTool>
		<IncludeBuildOutput>True</IncludeBuildOutput>
	</PropertyGroup>

	<PropertyGroup>
		<DefineConstants>$(DefineConstants);__UNO__</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="System.Xml" />
		<Reference Include="System.Xml.Linq" />
		<None Include="Uno.ShowMeTheXAML.MSBuild.targets" Pack="True" PackagePath="build" />

		<PackageReference Include="Microsoft.Build.Utilities.Core" Version="16.3.0" PrivateAssets="All" />
	</ItemGroup>

</Project>
